steps:
  
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install', '-Dmaven.test.skip=true']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/infosys-gcp-demo-project/spring-prometheus', '.']
    
images: ['gcr.io/infosys-gcp-demo-project/spring-prometheus']
